name: Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install

      - run: npm run build

      - uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: build
          path: docs

  deploy-s3:
    if: github.ref == 'refs/heads/main'

    needs:
      - build

    runs-on: ubuntu-latest

    # Allow write on id-token so we can use it to authenticate to AWS
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: docs

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::762706324393:role/cityos-sdk-deploy-v1
          aws-region: ap-northeast-1

      - name: Upload SDK to CDN
        run: |
          aws s3 cp --content-type="application/javascript" --cache-control="public, max-age=300" docs/index.js s3://gl-cityos-sdk-v1-ap-northeast-1/v1/shizuoka/yaizu/api.js
